### ISSUE TITLE
Search code

### ISSUE THREAD

**Issue by ln-dev7** [ln-dev7/sharuco#2]
Implement the possibility to search a code according to the description and according to the language, the search must be available on the pages "/explore" , "/dashboard" , "/user-id"

Please use SearchCode component ( /components/search-code.tsx )

**Comment by MbiamouRichy** [comment]
Hello Ln as I told you I'm here. It's true that I don't know NestJs yet but you never know.

**Comment by gausoft** [comment]
Interesting! Could also add **language and framework filtering**
