### ISSUE TITLE
Explore page codes not readable

### ISSUE THREAD

**Issue by eliotfgn** [ln-dev7/sharuco#42]
The content of the code blocs on explore page is not adapted to the blocs' width, and that makes the user slide to see the full content, spoiling the user experience.

**Comment by ln-dev7** [comment]
Hello @eliotfgn  there is the possibility to see the whole code and you have to know that some codes are long so I don't think there is another way

**Comment by eliotfgn** [comment]
Oh, I see. My bad. I thought we could modify the width of the box or adapt the fontsize.

**Comment by ln-dev7** [comment]
I understand but this case was meant to manage the layout of the grids. That's why there is a section dedicated to the details of the code

**Comment by ln-dev7** [comment]
I understand but this case was meant to manage the layout of the grids. That's why there is a section dedicated to the details of the code
