### ISSUE TITLE
Expandable snippet card

### ISSUE THREAD

**Issue by gausoft** [ln-dev7/sharuco#50]
Add expand icon on snippet card to have the code in fullscreen instead of scrolling horizontally. 

![Screen Shot 2023-04-01 at 07 28 39](https://user-images.githubusercontent.com/26385667/229272217-31ce929b-9076-4ba2-99a2-cf2f94f00c9c.png)

**Comment by ln-dev7** [comment]
When you click on the comment icon or on the description you are redirected to this page
<img width="443" alt="Sans titre" src="https://user-images.githubusercontent.com/62269693/229280269-fcd2e892-a967-4a72-8e8c-286335c09c92.png">

**Comment by gausoft** [comment]
Alright! But the fullscreen capability still useful in my opinion
