### ISSUE TITLE
Icons shrink

### ISSUE THREAD

**Issue by Patzi275** [ln-dev7/sharuco#60]
The header profile icon is stretched on mobile

Device: iphone 7 plus

![82B4D253-A1C1-423A-BFAA-2596A68FDC78](https://user-images.githubusercontent.com/87911547/231903245-2130e5a8-a882-4b93-95ed-ab65c3b1212a.jpeg)

**Comment by ln-dev7** [comment]
5S Simulator ...

![Capture d’écran du 2023-04-15 08-17-35](https://user-images.githubusercontent.com/62269693/232194851-af636b87-01ee-4d30-a42d-eca0e65cc0f8.png)
