### ISSUE TITLE
Feature request: Possibility to see the date when the code was added

### ISSUE THREAD

**Issue by bravemaster3** [ln-dev7/sharuco#62]
Hey, thank you very much for Sharuco. Very nice concept. I just tried it out, and I thought it might be interesting for the users to see when a code has been added. This will be especially helpful when sometimes, the syntax has changed in a language, making some codes obsolete...

**Comment by ln-dev7** [comment]
Done !

**Comment by bravemaster3** [comment]
Thanks!
