### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by mouafus** [ln-dev7/sharuco#95]
Add and "Click Away Listener" for some popup or dailog modal who need it for a better ux. For example, once the link has been copied, it would be interesting if the popup closed directly, I also find it important that the user closes this popup by clicking elsewhere  
<img width="1680" alt="Capture d’écran 2023-04-22 à 09 00 52" src="https://user-images.githubusercontent.com/45762805/233771180-12980964-4936-4900-b303-7bab6ef2a310.png">

Here, we have successfully modified his code but the user still has to click on "Cancel" to close the form, I think it should close automatically after the success of the operation. 

<img width="1680" alt="Capture d’écran 2023-04-22 à 09 04 31" src="https://user-images.githubusercontent.com/45762805/233771321-d7c11970-b04f-4b53-a678-a8eb2c274b42.png">

Here, we have successfully added a code but the form is still present, I think it should close automatically. If the idea is to allow multiple codes to be added, I suggest adding a checkbox to ask the user if he wants to leave the form open. 
<img width="1680" alt="Capture d’écran 2023-04-22 à 09 07 55" src="https://user-images.githubusercontent.com/45762805/233771798-510b81b7-bfb9-48bf-b36b-36670e3f7c7d.png">

**Comment by ln-dev7** [comment]
Done !
